server:
  port: 8080
  host: "0.0.0.0"

database:
  host: "localhost"
  port: 5432
  user: "tsimserver"
  password: "password"
  name: "tsimserver"
  sslmode: "disable"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"

jwt:
  secret: "your-super-secret-jwt-key-here-make-it-very-long-and-random"
  refresh_secret: "your-super-secret-refresh-jwt-key-here-make-it-different-and-long"
  access_token_expiry: 15  # minutes
  refresh_token_expiry: 7  # days

casbin:
  model_path: "casbin/model.conf"
  policy_path: "casbin/policy.csv"

websocket:
  endpoint: "/ws"
  read_buffer_size: 1024
  write_buffer_size: 1024

logging:
  level: "info" 